/**
 * Seed script: insert 10 example listings
 * Run with: npx ts-node --project tsconfig.json scripts/seed-listings.ts
 * (Make sure .env.local exists with your Supabase keys)
 */

import { createClient } from '@supabase/supabase-js'

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
)

const listings = [
  {
    project_name: 'The Pinnacle@Duxton',
    district: 11,
    area: 'Newton',
    floor_level: 28,
    unit_size_sqft: 1150,
    bedrooms: 3,
    bathrooms: 2,
    facing: 'SE',
    asking_price: 1_950_000,
    psf: 1696,
    tenure: 'freehold',
    top_year: 2009,
    listing_url: 'https://www.propertyguru.com.sg/example',
    agent_name: 'John Tan',
    agent_contact: '9123 4567',
  },
  {
    project_name: 'Marina Bay Residences',
    district: 1,
    area: 'Downtown',
    floor_level: 35,
    unit_size_sqft: 1320,
    bedrooms: 3,
    bathrooms: 2,
    facing: 'E',
    asking_price: 3_200_000,
    psf: 2424,
    tenure: 'freehold',
    top_year: 2020,
    listing_url: 'https://www.propertyguru.com.sg/example',
    agent_name: 'Sarah Lim',
    agent_contact: '9812 5678',
  },
  {
    project_name: 'The Sail @ Marina Bay',
    district: 4,
    area: 'Marina Bay',
    floor_level: 12,
    unit_size_sqft: 980,
    bedrooms: 2,
    bathrooms: 2,
    facing: 'N',
    asking_price: 1_680_000,
    psf: 1714,
    tenure: '999yr',
    top_year: 2012,
    listing_url: 'https://www.propertyguru.com.sg/example',
    agent_name: 'Michael Ng',
    agent_contact: '8765 4321',
  },
  {
    project_name: 'Bishan Park View',
    district: 20,
    area: 'Bishan',
    floor_level: 8,
    unit_size_sqft: 1100,
    bedrooms: 3,
    bathrooms: 2,
    facing: 'N',
    asking_price: 1_420_000,
    psf: 1291,
    tenure: '99yr',
    top_year: 1998,
    listing_url: 'https://www.propertyguru.com.sg/example',
    agent_name: 'David Wong',
    agent_contact: '9234 5678',
  },
  {
    project_name: 'The Interlace',
    district: 5,
    area: 'Buona Vista',
    floor_level: 18,
    unit_size_sqft: 1450,
    bedrooms: 3,
    bathrooms: 2,
    facing: 'W',
    asking_price: 2_100_000,
    psf: 1448,
    tenure: 'freehold',
    top_year: 2014,
    listing_url: 'https://www.propertyguru.com.sg/example',
    agent_name: 'Emily Chua',
    agent_contact: '9456 7890',
  },
  {
    project_name: 'Panorama Towers',
    district: 15,
    area: 'Marine Parade',
    floor_level: 22,
    unit_size_sqft: 1250,
    bedrooms: 3,
    bathrooms: 2,
    facing: 'SE',
    asking_price: 2_350_000,
    psf: 1880,
    tenure: 'freehold',
    top_year: 2006,
    listing_url: 'https://www.propertyguru.com.sg/example',
    agent_name: 'Peter Lee',
    agent_contact: '9567 8901',
  },
  {
    project_name: 'Lakeville Condo',
    district: 19,
    area: 'Sengkang',
    floor_level: 5,
    unit_size_sqft: 850,
    bedrooms: 2,
    bathrooms: 1,
    facing: 'N',
    asking_price: 695_000,
    psf: 818,
    tenure: '99yr',
    top_year: 2005,
    listing_url: 'https://www.propertyguru.com.sg/example',
    agent_name: 'Amy Tan',
    agent_contact: '8234 5678',
  },
  {
    project_name: 'Holland Vue',
    district: 10,
    area: 'Holland',
    floor_level: 15,
    unit_size_sqft: 1600,
    bedrooms: 4,
    bathrooms: 3,
    facing: 'NE',
    asking_price: 2_750_000,
    psf: 1719,
    tenure: 'freehold',
    top_year: 2008,
    listing_url: 'https://www.propertyguru.com.sg/example',
    agent_name: 'James Koh',
    agent_contact: '9678 9012',
  },
  {
    project_name: 'Pinnacle in the Sky',
    district: 9,
    area: 'Orchard',
    floor_level: 42,
    unit_size_sqft: 1350,
    bedrooms: 3,
    bathrooms: 2,
    facing: 'E',
    asking_price: 4_200_000,
    psf: 3111,
    tenure: 'freehold',
    top_year: 2019,
    listing_url: 'https://www.propertyguru.com.sg/example',
    agent_name: 'Linda Chua',
    agent_contact: '9789 0123',
  },
  {
    project_name: 'Lentor Modern',
    district: 26,
    area: 'Lentor',
    floor_level: 7,
    unit_size_sqft: 1050,
    bedrooms: 3,
    bathrooms: 2,
    facing: 'W',
    asking_price: 1_150_000,
    psf: 1095,
    tenure: '99yr',
    top_year: 2017,
    listing_url: 'https://www.propertyguru.com.sg/example',
    agent_name: 'Tom Lim',
    agent_contact: '9890 1234',
  },
]

async function seed() {
  console.log('🌱 Seeding 10 listings...')
  const { data, error } = await supabase.from('listings').insert(listings)
  if (error) {
    console.error('❌ Error:', error.message)
    process.exit(1)
  }
  console.log('✅ Done! Inserted 10 listings.')
  console.log('Go to http://localhost:3000 and refresh to see them.')
}

seed()
